apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: saas-ai-demo
spec:
  selector:
    app: saas-ai-demo
    component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
