apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: saas-ai-demo
spec:
  type: ClusterIP
  selector:
    app: saas-ai-demo
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
