apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: saas-ai-demo
spec:
  selector:
    app: saas-ai-demo
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
